language: php
php:
  - '5.6'
  - '7.0'
env:
  - TEST_SUITE=static
  - TEST_SUITE=unit
before_script:
  - composer self-update
  - composer install --dev
script:
  # Unit tests
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests; fi"\
  # Static tests
  - sh -c "if [ '$TEST_SUITE' = 'static' ]; then php vendor/bin/phpcs --report=xml --report-file=reports/phpcs.xml --standard=PSR2 --ignore=*/vendor/* -p -v ./; fi"\

notifications:
    on_success: never
    on_failure: always
