language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - composer self-update
  - composer install
script: phpunit --bootstrap vendor/autoload.php tests

notifications:
    on_success: never
    on_failure: always
